### ISSUE TITLE
Translate pages

### ISSUE THREAD

**Issue by cescoffier** [snowcamp/snowcamp-2018#4]
Pages should be also available in English

* Hugo documentation: https://gohugo.io/tutorials/create-a-multilingual-site/

**Comment by martinsson** [comment]
I can take this issue unless someone has already started

**Comment by martinsson** [comment]
work available in branch i18n

**Comment by martinsson** [comment]
Well now I have a few questions
1. Should the default language be french? I did not find a way to make the site select language based on the request header, so I forced french in config.toml
2. I haven't yet understood how to force a language for a sub page. Take /tickets for instance: Neither of /en/tickets or /tickets/en actually work. However this mecanisms seems to be the way to force the language at the baseUrl. Not really a question I guess, just sharing my thoughts.
3. Perhaps the best thing to do would be to extract all the translation keys in french only. That's the only part that risks creating merge conflicts. And while doing that best merge often.
